# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-31 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('urlshortner', '0005_auto_20180331_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('wee_url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='urlshortner.weeURL')),
            ],
        ),
        migrations.CreateModel(
            name='ClickEvnetManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
