# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-01 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClickEvnetManager',
        ),
    ]
