# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-17 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0002_auto_20180317_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
