# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-31 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import urlshortner.validators


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0004_auto_20180317_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeurl',
            name='url',
            field=models.CharField(max_length=220, validators=[urlshortner.validators.validate_url]),
        ),
    ]
