# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-01 05:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0005_auto_20180331_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeurl',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='weeurl',
            name='updated',
        ),
    ]
