# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-01 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0006_auto_20180401_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
